### ISSUE TITLE
 Error

### ISSUE THREAD

**Issue by songlinshu** [lpotthast/leptonic#1]
![image](https://github.com/lpotthast/leptonic/assets/45619496/2fed7b0c-e6e9-4ba5-ab4b-8c1dbd92337c)

**Comment by lpotthast** [comment]
Thanks for reporting this. Currently on vacation. Seems like leptos added a new optional prop to the `<A>` tag. Technically a breaking change.. The code now handles the previously missing property. Leptonic now requires leptos in version `0.4.3`. This is reflected in a changed Cargo.toml stating that exact version.
