### ISSUE TITLE
ContextMenu implementation

### ISSUE THREAD

**Issue by jembishop** [lpotthast/leptonic#19]
Hi there. 

I was wondering if you would be open to me contributing the right click context menu. Would probably take me a few weeks.
My current thoughts for this would be a set of components which could be composed in a context menu container. For example this menu: 

![](https://www.codingnepalweb.com/wp-content/uploads/2022/01/Custom-Right-Click-Context-Menu-in-HTML-CSS-JavaScript.jpg)

Would look something like this:

```html
<ContextMenu>
<MenuButton on:click=|_| do_preview()><Icon icon=BsIcon::BsEye/> "Preview" </MenuButton>
<SubMenu submenu=view!{<MenuButton> ... }><Icon icon=BsIcon::BsShare/> "Share" </SubMenu>
...
<Divider/>
<MenuButton>...
</ContextMenu>
```

Features: 

- [ ] Should be able to be spawned at mouse, or at customisable target button.  Probably separate these into two separate components.
- [ ] Should support both right and left clicks.
- [ ] Box should spawn at top left of target/mouse, but should relax this if the box were to go off the browser window.
- [ ] Clicking off menu  anywhere should close it. (I think this implies there must be a on click handler in the `<body>`)
- [ ] Submenus should be supported, which can be expanded with click or hover.
- [ ] Context menu should make sure it only can be activated within its parent.
- [ ] In the right click case one might need a component `<ContextMenuData data=...>` which sets a signal when the menu select event happens in its containing elements. This can be used by the context menus callbacks to implement different behaviour depending on the `ContextMenuData` data.
- [ ] Should be animated transition to submenu
- [ ] Corner rounding, hover background colour, border submenu expand icon, animated transition time, shadow should be able to be customised utilising CSS variables

Interested to see if you think this is the right approach. Thanks.

**Comment by lpotthast** [comment]
Hi, this would be a great addition! 

Give it a shot if you are still interested.

Your requirements / features seem reasonable.
Opening the menu near edges of a window (or any other specified container / space) should have to be handeled by opening the menu to either top, bottom, left or right, depending on the screen space available to each edge from the click location.

We may be able to use some of the components for the feature for other "menu"-like stuff. A `Select` component also "opens a menu" of options to choose from.
Having some reusable logic there would be great.

But having a rather specific `ContextMenu` implementation first is fine! Abstractions can always follow later.

**Comment by jembishop** [comment]
Thanks for getting back to me Lukas. I am still interested in implementing this feature, I will be on holiday throughout December so mid/late January is the realistic time I could deliver this feature, hopefully that fits in your time frame.

I'll make sure to respect those requirements you mentioned. 

In regards to the select I would agree that the code looks very similar, and the implementation of the context menu should be based on this, requiring some refactoring of the select component to facilitate this. 

A good first step is adding submenus, which can be generalised to subelements. I think in its most general sense it means allowing you to pass in `SelectOption`s which allow spawning of another `IntoView` element on hover in a sensible position. When there is an outside click, or hovering of another option in the parent menu, it should disappear.

- The `T`s which are required by `Select` should be changed to
```rust
enum MenuItem<T, O> {
    option: T,
    submenu: Option<Callback<T,  O>>
}
```
There can be an `Into` method for `T` which keeps backwards compatibility and ensures convenience for the simple case.

**Comment by jembishop** [comment]
Hi there, I might have to put this hold indefinitely due to personal commitments. Still would love to get round to doing it at some point, but haven't got the time at the moment, so don't wait for me!
