### ISSUE TITLE
Compilation Error - leptos_use

### ISSUE THREAD

**Issue by MinaMatta98** [lpotthast/leptonic#20]
Hello,

Could I please get some commentary regarding the following error?

![image](https://github.com/lpotthast/leptonic/assets/81748812/47b38fe3-32d8-4f59-a0a2-e54a643d883f)

**Comment by lighthx** [comment]
same to me, it seems to be incompatible with `nightly`

**Comment by lpotthast** [comment]
Yes, this is currently a limitation tracked in https://github.com/lpotthast/leptonic/issues/17. Looking into it.
