### ISSUE TITLE
leptonic.dev is down, can't create secure connection

### ISSUE THREAD

**Issue by jeffbski-sketch** [lpotthast/leptonic#26]
I believe something went wrong with the docs build of 0.3.0 and/or there is an issue with the certificate. Both brave and Safari are complaining about security when trying to go to the site such that it won't open it.

**Comment by jeffbski-sketch** [comment]
I believe certificate expired

**Comment by lpotthast** [comment]
Certificate is updated. Thanks for the heads up. Will be an automated process in the future.
