### ISSUE TITLE
Disabled `Radio` component is modifiable

### ISSUE THREAD

**Issue by Adrian-Blandin** [lpotthast/leptonic#35]
Hi,
On https://leptonic.dev/doc/radio, the disabled `Radio` state can still be changed by clicking on the label (`TOGGLE` text).

**Comment by lpotthast** [comment]
Hey, thanks for the notice!
The `TOGGLE` here is actually a button, supposed to toggle the selected state, mainly for testing purposes. Now that the radio elements have an inline style, the button is rendered besides it and looks like it's label... Ah..
The whole page is subject to change anyway. I will keep this in mind when rewriting it after radio buttons are build using the new/upcoming hooks/atoms.
