### ISSUE TITLE
Stack components and themes are invalid after the upgrade.

### ISSUE THREAD

**Issue by lhjok** [lpotthast/leptonic#6]
```rust <Stack orientation=StackOrientation::Vertical spacing=Size::Em(1.2)> ``` After upgrading, the Stack component Vertical has become Horizontal, and the theme effect is gone.

**Comment by lpotthast** [comment]
Make sure that both leptonic and leptonic-theme are up-to date. Maybe run a `cargo update` in your app. Try restarting your app, the current installation instructions are simpler than a version I had before but lead to changes in leptonic-theme only taking effect after a secondary trunk build...
(Reason: The build.rs file generates the theme, but trunk bundles static assets before the build.rs script is executed.. When doing a second build, trunk bundles the updated files (from the build.rs execution of the previous trunk build.)
There is a way around this, forcing build.rs execution before trunk kicks in, but this complicates the set up process.. I might have to switch that back.
